/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.AdminRole;

import Business.Business;
import Business.Course.CourseOffer;
import Business.Profiles.FacultyProfile;
import javax.swing.JPanel;
import javax.swing.DefaultComboBoxModel;
import java.awt.CardLayout;

/**
 *
 * @author Yaksha
 */
public class AssignFacultyJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel cardPanel;
    private String currentSemester = "Fall 2025";
    
    /**
     * Creates new form AssignFacultyJPanel
     */
    public AssignFacultyJPanel() {
        initComponents();
    }
    
    public void initialize(Business business, JPanel cardPanel) {
        this.business = business;
        this.cardPanel = cardPanel;
        loadCourses();
    }
    
    private void loadCourses() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        
        for (CourseOffer offer : business.getCourseOfferDirectory().getCourseOffersBySemester(currentSemester)) {
            String displayText = offer.getCourse().getCourseId() + " - " + offer.getCourse().getCourseName();
            model.addElement(displayText);
        }
        
        cmbCourse.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblFacultyPersonId = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        txtFacultyId = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Assign Faculty to Course");

        lblCourse.setText("Course :");

        lblFacultyPersonId.setText("Faculty Person ID :");

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFacultyPersonId)
                                    .addComponent(lblCourse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbCourse, 0, 185, Short.MAX_VALUE)
                                    .addComponent(txtFacultyId))))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblTitle)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyPersonId)
                    .addComponent(txtFacultyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssign)
                    .addComponent(btnBack))
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        String sel = (String) cmbCourse.getSelectedItem();
        if (sel == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pick a course.");
            return;
        }
        
        String courseId = sel.split(" - ")[0].trim();
        String facultyId = txtFacultyId.getText().trim();
        
        if (facultyId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter faculty person ID.");
            return;
        }
        
        // Find faculty
        FacultyProfile faculty = business.getFacultyDirectory().findFaculty(facultyId);
        if (faculty == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Faculty not found: " + facultyId);
            return;
        }
        
        // Find course offer
        CourseOffer targetOffer = null;
        for (CourseOffer offer : business.getCourseOfferDirectory().getCourseOffersBySemester(currentSemester)) {
            if (offer.getCourse().getCourseId().equals(courseId)) {
                targetOffer = offer;
                break;
            }
        }
        
        if (targetOffer == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Course offer not found");
            return;
        }
        
        // Assign faculty to course
        targetOffer.setAssignedFaculty(faculty);
        faculty.addAssignedCourse(targetOffer);
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Assigned " + faculty.getPerson().getFullName() + " to " + courseId);
        
        // Clear fields
        txtFacultyId.setText("");

    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((CardLayout)cardPanel.getLayout()).show(cardPanel, "workarea");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblFacultyPersonId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFacultyId;
    // End of variables declaration//GEN-END:variables
}
