/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

/**
 *
 * @author Yaksha
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabRegistrar = new javax.swing.JTabbedPane();
        CourseOffering = new javax.swing.JTabbedPane();
        ManageEnrollment = new javax.swing.JTabbedPane();
        FinancialReports = new javax.swing.JTabbedPane();
        Analytics = new javax.swing.JTabbedPane();
        MyProfile = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());

        tabRegistrar.addTab("Course Offering", CourseOffering);
        tabRegistrar.addTab("Manage Enrollment", ManageEnrollment);
        tabRegistrar.addTab("Financial Reports", FinancialReports);
        tabRegistrar.addTab("Analytics", Analytics);
        tabRegistrar.addTab("My Profile", MyProfile);

        add(tabRegistrar, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Analytics;
    private javax.swing.JTabbedPane CourseOffering;
    private javax.swing.JTabbedPane FinancialReports;
    private javax.swing.JTabbedPane ManageEnrollment;
    private javax.swing.JTabbedPane MyProfile;
    private javax.swing.JTabbedPane tabRegistrar;
    // End of variables declaration//GEN-END:variables
}
