/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;

/**
 *
 * @author Yaksha
 */
public class StudentRoleWorkAreaJPanel extends javax.swing.JPanel {

    private Business business;
    private StudentProfile student;
    private JPanel containerPanel;
    private CourseRegistrationJPanel coursePanel;
    private TranscriptJPanel transcriptPanel;
    private StudentFinancialJPanel paymentPanel;
    private GraduationAuditJPanel graduationPanel;
       private CourseWorkJPanel courseWorkJPanel;    /**
     * Creates new form StudentRoleWorkAreaJPanel
     */
    
    public StudentRoleWorkAreaJPanel(Business business, StudentProfile student, JPanel containerPanel) {
        initComponents();
        this.business = business;
        this.student = student;
        this.containerPanel = containerPanel;
        
        loadStudentPanels();
        
          tabStudent.addChangeListener(e -> {
            int selectedIndex = tabStudent.getSelectedIndex();
            if (selectedIndex == 0) {
                coursePanel.refreshPanel();
            } else if (selectedIndex == 1) {
                transcriptPanel.refreshPanel();
            } else if (selectedIndex == 2) {
                paymentPanel.refreshPanel();
            } else if (selectedIndex == 3) {
                graduationPanel.refreshPanel();
            }
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabStudent = new javax.swing.JTabbedPane();
        CourseRegistration = new javax.swing.JPanel();
        Transcripts = new javax.swing.JPanel();
        Audits = new javax.swing.JPanel();
        Financial = new javax.swing.JPanel();
        Profile = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        tabStudent.addTab("Course Registration", CourseRegistration);
        tabStudent.addTab("Transcripts", Transcripts);
        tabStudent.addTab("Graduation Audits", Audits);
        tabStudent.addTab("Financial", Financial);
        tabStudent.addTab("CourseWork", Profile);
        tabStudent.addTab("My Profile", jPanel1);

        add(tabStudent, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Audits;
    private javax.swing.JPanel CourseRegistration;
    private javax.swing.JPanel Financial;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel Transcripts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabStudent;
    // End of variables declaration//GEN-END:variables

    private void loadStudentPanels() {
tabStudent.removeAll();
    
    // Create panels and assign to fields (don't redeclare!)
    coursePanel = new CourseRegistrationJPanel(
        student, 
        business.getCourseOfferDirectory(), 
        "Fall 2025"
    );
    tabStudent.addTab("Course Registration", coursePanel);
    
    transcriptPanel = new TranscriptJPanel(student);
    tabStudent.addTab("Transcript", transcriptPanel);
    
    paymentPanel = new StudentFinancialJPanel(student);
    tabStudent.addTab("Pay Tuition", paymentPanel);
    
    graduationPanel = new GraduationAuditJPanel(student);
    tabStudent.addTab("Graduation Audit", graduationPanel);
    
    
    CourseWorkJPanel courseWorkPanel = new CourseWorkJPanel(student);
    tabStudent.addTab("CourseWork", courseWorkPanel);
    
        

    StudentProfileJPanel profilePanel = new StudentProfileJPanel(student);
    tabStudent.addTab("My Profile", profilePanel);
    }
    
    public void refreshPanel() {  
    filterBySemester();
}

    private void filterBySemester() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
