/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.Business;
import Business.ConfigureABusiness;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import Business.Profiles.*;
import UserInterface.AdminRole.AdminRoleWorkAreaJPanel;
import UserInterface.FacultyRole.FacultyRoleWorkAreaJPanel;
import UserInterface.RegistrarRole.RegistrarRoleWorkAreaJPanel;
import UserInterface.StudentRole.StudentRoleWorkAreaJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author Yaksha
 */
public class UniversityMainJFrame extends javax.swing.JFrame {

    Business business;
    private JPanel containerPanel;
    private CardLayout cardLayout;
    
    /**
     * Creates new form UniversityMainJFrame
     */
    public UniversityMainJFrame() {
        initComponents();
        business = ConfigureABusiness.configure();
        
        cardLayout = new CardLayout();
        containerPanel = new JPanel(cardLayout);
        containerPanel.add(loginPanel, "login");
        getContentPane().add(containerPanel);
        cardLayout.show(containerPanel, "login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("University Model ");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPassword)))
                        .addGap(31, 31, 31)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(btnLogin))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblTitle)
                .addGap(36, 36, 36)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        getContentPane().add(loginPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
     String username = txtUsername.getText();
     String password = txtPassword.getText();
        
        // Validate input
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter both username and password!", 
                "Input Required", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Authenticate user
        UserAccountDirectory uad = business.getUserAccountDirectory();
        UserAccount userAccount = uad.authenticateUser(username, password);
        
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, 
                "Invalid username or password!", 
                "Login Failed", 
                JOptionPane.ERROR_MESSAGE);
            // Clear password field for security
            txtPassword.setText("");
            return;
        }
        
        // Get role object
        Profile roleObj = userAccount.getAssociatedPersonRole();
        
        // Remove any existing work area panels
        if (containerPanel.getComponentCount() > 1) {
            while (containerPanel.getComponentCount() > 1) {
                containerPanel.remove(1);
            }
        }
        
        // Create appropriate work area based on role
        if (roleObj instanceof EmployeeProfile) {
            AdminRoleWorkAreaJPanel adminPanel = new AdminRoleWorkAreaJPanel(business, containerPanel);
            containerPanel.add(adminPanel, "workarea");
            cardLayout.show(containerPanel, "workarea");
            JOptionPane.showMessageDialog(this, 
                "Welcome Admin: " + roleObj.getPerson().getFullName() + "!", 
                "Login Successful", 
                JOptionPane.INFORMATION_MESSAGE);
        } else if (roleObj instanceof RegistrarProfile) {
            RegistrarProfile registrar = (RegistrarProfile) roleObj;
            RegistrarRoleWorkAreaJPanel registrarPanel = new RegistrarRoleWorkAreaJPanel(business, registrar, containerPanel);
            containerPanel.add(registrarPanel, "workarea");
            cardLayout.show(containerPanel, "workarea");
            JOptionPane.showMessageDialog(this, 
                "Welcome Registrar: " + registrar.getPerson().getFullName() + "!", 
                "Login Successful", 
                JOptionPane.INFORMATION_MESSAGE);
        } else if (roleObj instanceof FacultyProfile) {
            FacultyProfile faculty = (FacultyProfile) roleObj;
            FacultyRoleWorkAreaJPanel facultyPanel = new FacultyRoleWorkAreaJPanel(business, faculty, containerPanel);
            containerPanel.add(facultyPanel, "workarea");
            cardLayout.show(containerPanel, "workarea");
            JOptionPane.showMessageDialog(this, 
                "Welcome Faculty: " + faculty.getPerson().getFullName() + "!", 
                "Login Successful", 
                JOptionPane.INFORMATION_MESSAGE);
        } else if (roleObj instanceof StudentProfile) {
            StudentProfile student = (StudentProfile) roleObj;
            StudentRoleWorkAreaJPanel studentPanel = new StudentRoleWorkAreaJPanel(business, student, containerPanel);
            containerPanel.add(studentPanel, "workarea");
            cardLayout.show(containerPanel, "workarea");
            JOptionPane.showMessageDialog(this, 
                "Welcome Student: " + student.getPerson().getFullName() + "!", 
                "Login Successful", 
                JOptionPane.INFORMATION_MESSAGE);
        }
        
        // Clear login fields
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    public void showLoginScreen() {
        cardLayout.show(containerPanel, "login");
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversityMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversityMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversityMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversityMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversityMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
