/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.AdminRole;

/**
 *
 * @author Yaksha
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminRoleWorkAreaJPanel
     */
    public AdminRoleWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabAdmin = new javax.swing.JTabbedPane();
        UserManagement = new javax.swing.JTabbedPane();
        RegisterPerson = new javax.swing.JTabbedPane();
        StudentRecords = new javax.swing.JTabbedPane();
        FacultyRecords = new javax.swing.JTabbedPane();
        Analytics = new javax.swing.JTabbedPane();
        Myprofile = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());

        tabAdmin.addTab("User Management", UserManagement);
        tabAdmin.addTab("Register Person", RegisterPerson);
        tabAdmin.addTab("Student Records", StudentRecords);
        tabAdmin.addTab("Faculty Records", FacultyRecords);
        tabAdmin.addTab("Analytics", Analytics);
        tabAdmin.addTab("My Profile", Myprofile);

        add(tabAdmin, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Analytics;
    private javax.swing.JTabbedPane FacultyRecords;
    private javax.swing.JTabbedPane Myprofile;
    private javax.swing.JTabbedPane RegisterPerson;
    private javax.swing.JTabbedPane StudentRecords;
    private javax.swing.JTabbedPane UserManagement;
    private javax.swing.JTabbedPane tabAdmin;
    // End of variables declaration//GEN-END:variables
}
