/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RegistrarRole;

import Business.Business;
import Business.Course.CourseEnrollment;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;

/**
 *
 * @author Yaksha
 */
public class FianacialReportJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel cardPanel;
    /**
     * Creates new form FianacialReportJPanel
     */

    public FianacialReportJPanel() {
        initComponents();
    }
    
    public void initialize(Business business, JPanel cardPanel) {
        this.business = business;
        this.cardPanel = cardPanel;
        loadFinancialData();
    }

    private void loadFinancialData() {
        DefaultTableModel model = (DefaultTableModel) tblFinance.getModel();
        model.setRowCount(0);
        
        double totalBilled = 0.0;
        double totalPaid = 0.0;
        double totalRefunded = 0.0;
        double totalOutstanding = 0.0;
        
        for (StudentProfile student : business.getStudentDirectory().getStudentList()) {
            double studentBilled = 0.0;
            double studentPaid = 0.0;
            double studentRefunded = 0.0;
            
            for (CourseEnrollment enrollment : student.getEnrollments()) {
                studentBilled += enrollment.getTuitionAmount();
                if (enrollment.isTuitionPaid()) {
                    studentPaid += enrollment.getTuitionAmount();
                }
            }
            
            double studentOutstanding = studentBilled - studentPaid - studentRefunded;
            
            if (studentBilled > 0) {
                model.addRow(new Object[]{
                    student.getPerson().getPersonId(),
                    String.format("$%.2f", studentBilled),
                    String.format("$%.2f", studentPaid),
                    String.format("$%.2f", studentRefunded),
                    String.format("$%.2f", studentOutstanding)
                });
                
                totalBilled += studentBilled;
                totalPaid += studentPaid;
                totalRefunded += studentRefunded;
                totalOutstanding += studentOutstanding;
            }
        }
        
        lblCollected.setText("Collected: $" + String.format("%.2f", totalPaid));
        lblUnpaid.setText("Unpaid: $" + String.format("%.2f", totalOutstanding));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFinance = new javax.swing.JTable();
        lblCollected = new javax.swing.JLabel();
        lblUnpaid = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Finance & Reconciliation (Term: …)");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblFinance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Billed", "Paid", "Refunded", "Outstanding"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFinance);

        lblCollected.setText("Collected :");

        lblUnpaid.setText("Unpaid:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnpaid)
                    .addComponent(lblCollected))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblCollected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnpaid)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       ((CardLayout)cardPanel.getLayout()).show(cardPanel, "workarea");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCollected;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnpaid;
    private javax.swing.JTable tblFinance;
    // End of variables declaration//GEN-END:variables
}
