/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RegistrarRole;

import Business.Business;
import Business.Course.Course;
import Business.Course.CourseOffer;
import Business.Profiles.FacultyProfile;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;

/**
 *
 * @author Yaksha
 */
public class StudentOfferingJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel cardPanel;
    private String currentSemester = "Fall 2025";
    
    /**
     * Creates new form StudentOfferingJPanel
     */
    
    public StudentOfferingJPanel() {
        initComponents();
    }

    public void initialize(Business business, JPanel cardPanel) {
        this.business = business;
        this.cardPanel = cardPanel;
        loadOffers();
    }
    
    private void loadOffers() {
        DefaultTableModel model = (DefaultTableModel) tblOffers.getModel();
        model.setRowCount(0);
        
        for (CourseOffer offer : business.getCourseOfferDirectory().getCourseOffersBySemester(currentSemester)) {
            String facultyId = offer.getAssignedFaculty() != null ? 
                offer.getAssignedFaculty().getPerson().getPersonId() : "Not Assigned";
            
            model.addRow(new Object[]{
                offer.getCourse().getCourseId(),
                offer.getCourse().getCourseName(),
                offer.getCapacity(),
                offer.getRoomLocation() != null ? offer.getRoomLocation() : "",
                offer.getSchedule() != null ? offer.getSchedule() : "",
                facultyId,
                offer.getEnrolledCount()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCourseNum = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        lblCapacity = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOffers = new javax.swing.JTable();
        txtCapacity = new javax.swing.JTextField();
        lblRoom = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblFaculty = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtFacultyId = new javax.swing.JTextField();
        lblCourseNum = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        btnAssign.setText("Assign Faculty");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblCapacity.setText("Capacity:");

        tblOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course #", "Course", "Capacity", "Room", "Time", "FacultyIdl", "Enrolled"
            }
        ));
        jScrollPane2.setViewportView(tblOffers);

        lblRoom.setText("Room:");

        lblTime.setText("Time:");

        lblFaculty.setText("Faculty Person ID:");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Course Offering Management (Term: …)");

        lblCourseNum.setText("Course #");

        btnCreate.setText("Create/Offer");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Selected");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblCourseNum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblTitle)
                        .addGap(44, 44, 44)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoom)
                                    .addComponent(lblTime)
                                    .addComponent(lblFaculty)
                                    .addComponent(lblCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCreate)
                                .addGap(60, 60, 60)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCourseNum)
                                .addComponent(txtCapacity)
                                .addComponent(txtRoom)
                                .addComponent(txtTime)
                                .addComponent(txtFacultyId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnUpdate)
                                .addGap(48, 48, 48)
                                .addComponent(btnAssign))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNum)
                    .addComponent(txtCourseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacity)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoom)
                    .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaculty)
                    .addComponent(txtFacultyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnAssign))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:

        int row = tblOffers.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row");
            return;
        }
        
        String courseId = String.valueOf(tblOffers.getValueAt(row, 0));
        String facultyId = txtFacultyId.getText().trim();
        
        if (facultyId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter Faculty Person ID");
            return;
        }
        
        FacultyProfile faculty = business.getFacultyDirectory().findFaculty(facultyId);
        if (faculty == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Faculty not found: " + facultyId);
            return;
        }
        
        // Find and update the course offer
        for (CourseOffer offer : business.getCourseOfferDirectory().getCourseOffersBySemester(currentSemester)) {
            if (offer.getCourse().getCourseId().equals(courseId)) {
                offer.setAssignedFaculty(faculty);
                faculty.addAssignedCourse(offer);
                break;
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Assigned " + facultyId + " to " + courseId);
        loadOffers();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String courseId = txtCourseNum.getText().trim();
        String capStr = txtCapacity.getText().trim();
        
        if (courseId.isEmpty() || capStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Course # and Capacity required");
            return;
        }
        
        int capacity;
        try {
            capacity = Integer.parseInt(capStr);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Capacity must be a number");
            return;
        }
        
        // Find the course
        Course course = business.getCourseDirectory().findCourse(courseId);
        if (course == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Course not found: " + courseId);
            return;
        }
        
        // Create course offer
        String offerId = courseId + "-" + currentSemester.replace(" ", "") + "-" + System.currentTimeMillis();
        CourseOffer offer = business.getCourseOfferDirectory().newCourseOffer(offerId, course, currentSemester, capacity);
        offer.setRoomLocation(txtRoom.getText().trim());
        offer.setSchedule(txtTime.getText().trim());
        
        javax.swing.JOptionPane.showMessageDialog(this, "Offer created for " + courseId + " with " + capacity + " seats");
        loadOffers();

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        ((CardLayout)cardPanel.getLayout()).show(cardPanel, "workarea");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblOffers.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row");
            return;
        }
        
        String courseId = String.valueOf(tblOffers.getValueAt(row, 0));
        
        int capacity;
        try {
            capacity = Integer.parseInt(txtCapacity.getText().trim());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter numeric capacity");
            return;
        }
        
        // Find and update the course offer
        CourseOffer targetOffer = null;
        for (CourseOffer offer : business.getCourseOfferDirectory().getCourseOffersBySemester(currentSemester)) {
            if (offer.getCourse().getCourseId().equals(courseId)) {
                targetOffer = offer;
                break;
            }
        }
        
        if (targetOffer == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Offer not found");
            return;
        }
        
        // Update capacity and details
        targetOffer.setCapacity(capacity);
        targetOffer.setRoomLocation(txtRoom.getText().trim());
        targetOffer.setSchedule(txtTime.getText().trim());
        
        javax.swing.JOptionPane.showMessageDialog(this, "Capacity/Room/Time updated");
        loadOffers();

    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblCourseNum;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOffers;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtCourseNum;
    private javax.swing.JTextField txtFacultyId;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
