/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.AdminRole;

/**
 *
 * @author Yaksha
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminRoleWorkAreaJPanel
     */
    public AdminRoleWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabAdmin = new javax.swing.JTabbedPane();
        UserManagement = new javax.swing.JTabbedPane();
        RegisterPerson = new javax.swing.JTabbedPane();
        StudentRecords = new javax.swing.JTabbedPane();
        FacultyRecords = new javax.swing.JTabbedPane();
        Analytics = new javax.swing.JTabbedPane();
        MyProfile = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());

        TabAdmin.addTab("UserManagemenet", UserManagement);
        TabAdmin.addTab("RegisterPerson", RegisterPerson);
        TabAdmin.addTab("StudentRecords", StudentRecords);
        TabAdmin.addTab("FacultyRecords", FacultyRecords);
        TabAdmin.addTab("Analytics", Analytics);
        TabAdmin.addTab("MyProfile", MyProfile);

        add(TabAdmin, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Analytics;
    private javax.swing.JTabbedPane FacultyRecords;
    private javax.swing.JTabbedPane MyProfile;
    private javax.swing.JTabbedPane RegisterPerson;
    private javax.swing.JTabbedPane StudentRecords;
    private javax.swing.JTabbedPane TabAdmin;
    private javax.swing.JTabbedPane UserManagement;
    // End of variables declaration//GEN-END:variables
}
