/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.FacultyRole;

/**
 *
 * @author Yaksha
 */
public class FacultyRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyRoleWorkAreaJPanel
     */
    public FacultyRoleWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabFaculty = new javax.swing.JTabbedPane();
        MyCourse = new javax.swing.JTabbedPane();
        Grade = new javax.swing.JTabbedPane();
        Performance = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());

        tabFaculty.addTab("My Course ", MyCourse);
        tabFaculty.addTab("Grade Student", Grade);
        tabFaculty.addTab("Performance Reports", Performance);
        tabFaculty.addTab("My Profile", Profile);

        add(tabFaculty, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Grade;
    private javax.swing.JTabbedPane MyCourse;
    private javax.swing.JTabbedPane Performance;
    private javax.swing.JTabbedPane Profile;
    private javax.swing.JTabbedPane tabFaculty;
    // End of variables declaration//GEN-END:variables
}
