/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.FacultyRole;

import Business.Business;
import Business.Profiles.FacultyProfile;
import Business.Course.CourseOffer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
/**
 *
 * @author Yaksha
 */
public class CourseManagementJPanel extends javax.swing.JPanel {

    private Business business;
    private FacultyProfile faculty;
    private JPanel cardPanel;
    /**
     * Creates new form CourseManagementJPanel
     */
    public CourseManagementJPanel() {
        initComponents();
    }

     public void initialize(Business business, FacultyProfile faculty, JPanel cardPanel) {
        this.business = business;
        this.faculty = faculty;
        this.cardPanel = cardPanel;
        loadCourses();
    }
    
    private void loadCourses() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        // Load courses assigned to this faculty
        for (CourseOffer offer : faculty.getAssignedCourses()) {
            String status = offer.isEnrollmentOpen() ? "Open" : "Closed";
            String syllabus = offer.getSyllabus() != null ? offer.getSyllabus() : "Not uploaded";
            
            model.addRow(new Object[]{
                offer.getCourse().getCourseId(),
                offer.getCourse().getCourseName(),
                offer.getCourse().getDescription(),
                offer.getSchedule() != null ? offer.getSchedule() : "TBD",
                offer.getCapacity(),
                status,
                syllabus
            });
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpload = new javax.swing.JButton();
        lblTitleCourse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnEnrollment = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        btnUpload.setText("Upload/Modify syllabus");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        lblTitleCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleCourse.setText("Course Management");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Title", "Description", "Schedule", "Capacity", "Enrollement Status", "Syllabus"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Course");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnEnrollment.setText("Enrollment Status");
        btnEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollmentActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEnrollment)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(lblTitleCourse)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleCourse)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView)
                    .addComponent(btnEdit)
                    .addComponent(btnEnrollment)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefresh)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(btnUpload))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course first!");
            return;
        }
        
        String courseId = (String) jTable1.getValueAt(row, 0);
        
        // Simple input dialog for syllabus text
        String syllabusText = javax.swing.JOptionPane.showInputDialog(this, 
            "Enter syllabus text:", 
            "Upload Syllabus");
        
        if (syllabusText != null && !syllabusText.trim().isEmpty()) {
            // Find the course offer and update syllabus
            for (CourseOffer offer : faculty.getAssignedCourses()) {
                if (offer.getCourse().getCourseId().equals(courseId)) {
                    offer.setSyllabus(syllabusText);
                    jTable1.setValueAt(syllabusText, row, 6);
                    javax.swing.JOptionPane.showMessageDialog(this, "Syllabus uploaded successfully!");
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course first!");
            return;
        }
        
        String courseNum = (String) jTable1.getValueAt(row, 0);
        String courseTitle = (String) jTable1.getValueAt(row, 1);
        String description = (String) jTable1.getValueAt(row, 2);
        String schedule = (String) jTable1.getValueAt(row, 3);
        String capacity = String.valueOf(jTable1.getValueAt(row, 4));
        String status = (String) jTable1.getValueAt(row, 5);
        String syllabus = (String) jTable1.getValueAt(row, 6);
        
        String details = "Course Number: " + courseNum + "\n" +
            "Course Title: " + courseTitle + "\n" +
            "Description: " + description + "\n" +
            "Schedule: " + schedule + "\n" +
            "Capacity: " + capacity + "\n" +
            "Enrollment Status: " + status + "\n\n" +
            "Syllabus:\n" +
            "----------------------------------------\n" +
            syllabus;
        
        javax.swing.JTextArea textArea = new javax.swing.JTextArea(details);
        textArea.setRows(20);
        textArea.setColumns(50);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setEditable(false);
        
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        
        javax.swing.JOptionPane.showMessageDialog(this, scrollPane,
            "Course Details - " + courseNum,
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course first!");
            return;
        }
        
        String courseId = (String) jTable1.getValueAt(row, 0);
        
        // Find the course offer
        for (CourseOffer offer : faculty.getAssignedCourses()) {
            if (offer.getCourse().getCourseId().equals(courseId)) {
                // Edit Schedule
                String newSchedule = javax.swing.JOptionPane.showInputDialog(this, 
                    "Edit Schedule:", 
                    offer.getSchedule());
                if (newSchedule != null && !newSchedule.trim().isEmpty()) {
                    offer.setSchedule(newSchedule);
                    jTable1.setValueAt(newSchedule, row, 3);
                }
                
                javax.swing.JOptionPane.showMessageDialog(this, "Course updated successfully!");
                return;
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollmentActionPerformed
        // TODO add your handling code here:
       int row = jTable1.getSelectedRow();
        
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course first!");
            return;
        }
        
        String courseId = (String) jTable1.getValueAt(row, 0);
        
        // Find and toggle enrollment status
        for (CourseOffer offer : faculty.getAssignedCourses()) {
            if (offer.getCourse().getCourseId().equals(courseId)) {
                offer.setEnrollmentOpen(!offer.isEnrollmentOpen());
                String newStatus = offer.isEnrollmentOpen() ? "Open" : "Closed";
                jTable1.setValueAt(newStatus, row, 5);
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Enrollment status changed to: " + newStatus);
                return;
            }
        }
    }//GEN-LAST:event_btnEnrollmentActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadCourses();
        javax.swing.JOptionPane.showMessageDialog(this, "Refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((CardLayout)cardPanel.getLayout()).show(cardPanel, "workarea");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnrollment;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitleCourse;
    // End of variables declaration//GEN-END:variables
}
