/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.FacultyRole;

/**
 *
 * @author Yaksha
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyWorkAreaJPanel
     */
    public FacultyWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabFaculty = new javax.swing.JTabbedPane();
        MyCourses = new javax.swing.JTabbedPane();
        GradeStudents = new javax.swing.JTabbedPane();
        PerformanceReport = new javax.swing.JTabbedPane();
        MyProfile = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());

        tabFaculty.addTab("My Courses", MyCourses);
        tabFaculty.addTab("Grade Students", GradeStudents);
        tabFaculty.addTab("Performance Reports", PerformanceReport);
        tabFaculty.addTab("My Profile", MyProfile);

        add(tabFaculty, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane GradeStudents;
    private javax.swing.JTabbedPane MyCourses;
    private javax.swing.JTabbedPane MyProfile;
    private javax.swing.JTabbedPane PerformanceReport;
    private javax.swing.JTabbedPane tabFaculty;
    // End of variables declaration//GEN-END:variables
}
