/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.StudentRole;

/**
 *
 * @author Yaksha
 */
public class StudentRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentRoleWorkAreaJPanel
     */
    public StudentRoleWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabStudent = new javax.swing.JTabbedPane();
        CourseRegistration = new javax.swing.JTabbedPane();
        Transcripts = new javax.swing.JTabbedPane();
        Audits = new javax.swing.JTabbedPane();
        Financial = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());

        tabStudent.addTab("Course Registration", CourseRegistration);
        tabStudent.addTab("Transcripts", Transcripts);
        tabStudent.addTab("Graduation Audits", Audits);
        tabStudent.addTab("Financial", Financial);
        tabStudent.addTab("My Profile", Profile);

        add(tabStudent, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Audits;
    private javax.swing.JTabbedPane CourseRegistration;
    private javax.swing.JTabbedPane Financial;
    private javax.swing.JTabbedPane Profile;
    private javax.swing.JTabbedPane Transcripts;
    private javax.swing.JTabbedPane tabStudent;
    // End of variables declaration//GEN-END:variables
}
